title: Oana Barbu
description: Research and writings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  footnote_backlink: "&#8617;"
